# Generated by Django 3.1.6 on 2021-02-17 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_country', to='users.country')),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_country', to='users.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_state', to='users.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_approved', models.BooleanField(blank=True, default=False, help_text='Designates whether the user is approved.', null=True, verbose_name='approve status')),
                ('is_admin', models.BooleanField(blank=True, default=False, help_text='Designates whether the user is admin.', null=True, verbose_name='admin status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone', models.IntegerField(unique=True)),
                ('language', models.CharField(default='EN', max_length=30, verbose_name='language')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateField(null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.CharField(blank=True, max_length=150, verbose_name='bio')),
                ('cast', models.CharField(choices=[('G', 'GENERAL'), ('O', 'OBC'), ('Sc', 'SC'), ('St', 'ST')], max_length=2)),
                ('married', models.BooleanField(default=False)),
                ('occupation_type', models.CharField(choices=[('G', 'Goverment'), ('P', 'Private'), ('F', 'Farmer'), ('S', 'Self'), ('N', 'None')], max_length=2)),
                ('occupation_detail', models.CharField(blank=True, max_length=500)),
                ('address_detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='users.city', verbose_name='city')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='users.country', verbose_name='country')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrole')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='users.state', verbose_name='state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
